name: church_diary_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.12+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^2.3.0
  splashscreen: ^1.3.5
  provider: ^4.3.2+2
  cloud_firestore: ^0.14.4
  firebase_helpers: ^0.2.1
  firebase_core: ^0.5.2
  toast: ^0.1.5
  image_picker: ^0.6.7+22
  firebase_storage: ^5.2.0
  firebase_analytics: ^5.0.6
  cached_network_image: ^2.5.0
  multi_masked_formatter: ^0.1.1
  font_awesome_flutter: ^8.12.0
  flutter_icons: ^1.1.0
  pdf: ^2.0.0
  characters: ^1.0.0
  path_provider: ^1.6.28
  url_launcher: ^5.7.10
  printing: ^4.0.0
  image_downloader: ^0.20.1
  http: ^0.12.2
#  dio: ^3.0.10
  firebase_image: ^0.3.0

  # google login
  google_sign_in: ^4.5.6

  # apple login
  apple_sign_in: ^0.1.0
  firebase_auth: ^0.18.3
  flutter_secure_storage: ^3.3.5

  # 다국어 처리
  easy_localization: #^2.3.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/animal/
    - assets/icon/
    - fonts/NanumMyeongjo.ttf
    - fonts/NanumMyeongjoExtraBold.ttf

  fonts:
    - family: Nanum
      fonts:
        - asset: fonts/NanumMyeongjo.ttf
        - asset: fonts/NanumMyeongjoExtraBold.ttf
